# NUMPY

In [3]:
import numpy as np

In [4]:
simple_list=[6,7,9]
             
np.array(simple_list)

array([6, 7, 9])

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
array_list=[[1,2,3],[3,4,5],[6,7,8]]
np.array(array_list)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.arange(5,65)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [10]:
np.arange[1,100]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [11]:
# create a whole number upto 100

np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

In [14]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.linspace(0,2,8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [21]:
np.random.rand(2,4)  #uniform distribution

array([[0.14079952, 0.53780801, 0.41615551, 0.67759688],
       [0.15934417, 0.49754404, 0.40131952, 0.62083233]])

In [22]:
arr=np.random.randn(2,4)   #normal distribution
arr

array([[-0.51788066,  1.84062304,  0.39481243,  1.28231691],
       [ 1.07591043,  0.85624968,  2.8676978 ,  0.01101267]])

In [23]:
np.random.randint(2,10)

5

In [24]:
np.random.randint(20,56,100)

array([40, 50, 21, 40, 25, 29, 31, 50, 53, 46, 30, 34, 27, 22, 35, 52, 27,
       30, 46, 31, 46, 24, 48, 22, 54, 24, 49, 43, 50, 40, 43, 52, 24, 31,
       39, 50, 41, 32, 38, 31, 21, 29, 46, 37, 36, 27, 27, 48, 23, 29, 29,
       46, 28, 21, 46, 38, 49, 32, 32, 28, 22, 34, 29, 54, 49, 38, 22, 54,
       26, 44, 32, 23, 23, 44, 29, 48, 51, 43, 29, 35, 29, 49, 21, 34, 48,
       30, 54, 21, 41, 55, 25, 31, 31, 27, 38, 46, 28, 49, 36, 33])

In [25]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
rand_array=np.random.randint(0,100)
rand_array

61

In [32]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
rand_array=np.random.randint(20,56,100)

In [35]:
np.random.randint(0,100)

58

In [37]:
rand_array.min()

20

In [38]:
rand_array.max()

55

In [39]:
rand_array.argmin()

37

In [40]:
rand_array.argmax()

28

In [41]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
a=np.random.rand(2,3)
a

array([[0.98559621, 0.43521344, 0.64547677],
       [0.38283686, 0.27997311, 0.41169845]])

In [44]:
a.T

array([[0.98559621, 0.38283686],
       [0.43521344, 0.27997311],
       [0.64547677, 0.41169845]])

In [45]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
sample_array[8]

18

In [47]:
sample_array[2:5]

array([12, 13, 14])

In [48]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [49]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [50]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001])

## Two dimensional array

In [51]:
sample_matrix=np.array(([60,20,1,2],[34,54,23,78],[2,6,45,90]))
sample_matrix


array([[60, 20,  1,  2],
       [34, 54, 23, 78],
       [ 2,  6, 45, 90]])

In [52]:
sample_matrix[0][2]

1

In [53]:
sample_matrix[2,:]

array([ 2,  6, 45, 90])

In [54]:
sample_matrix[2]

array([ 2,  6, 45, 90])

In [55]:
sample_matrix[1,2]

23

In [56]:
sample_matrix[:,(3,2)]

array([[ 2,  1],
       [78, 23],
       [90, 45]])

## Selection techniques

In [57]:
np.array=((1,2,3))

In [58]:
np.array


(1, 2, 3)

In [59]:
sample_array=np.arange(1,20)

In [60]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [61]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [62]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [63]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [64]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [65]:
np.max(sample_array)

19

In [66]:
np.min(sample_array)

1

In [67]:
np.argmax(sample_array)

18

In [68]:
np.argmin(sample_array)

0

In [69]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [70]:
np.mean(sample_array)

10.0

In [71]:
np.var(sample_array)

30.0

In [72]:
np.std(sample_array)

5.477225575051661

In [73]:
array=np.random.randn(3,4)
array

array([[-1.01195819,  1.74673803,  0.34685818, -0.26802306],
       [-1.77521285, -0.04417573, -0.26307825, -0.28901293],
       [-1.15121051, -0.02720957, -0.03885357, -1.0113499 ]])

In [74]:
np.round(array,decimals=2)

array([[-1.01,  1.75,  0.35, -0.27],
       [-1.78, -0.04, -0.26, -0.29],
       [-1.15, -0.03, -0.04, -1.01]])